config/routes.rb
Rails.application.routes.draw do
    root to: "queries#index"
  devise_for :users
  resources :queries, only: [:index]

  get "/home" => "queries#home"
  post "/saved" => "queries#saved"
  get "/near_me" => "queries#near_me"
  get "/show" => "queries#show"
  get "/saved_places" => "queries#saved_places"

 end

app/models/query.rb
class Query < ActiveRecord::Base

belongs_to :user

	def setup
		@foursquare_id = ENV["foursquare_id"]
		@foursquare_secret = ENV["foursquare_secret"]
		@client = Foursquare2::Client.new(:client_id => @foursquare_id, :client_secret => @foursquare_secret)
	end

	def explore_by_location(search_term)
		response = setup.explore_venues(:near => search_term, :v => 20140806, :m => "foursquare", :section => "sights", :venuePhotos => 1)
		get_info(response)
		#use Query.create(name: "ef", something.. ) here.
	end

	def explore_by_coords(coords)
		response = setup.explore_venues(:ll => coords, :v => 20140806, :m => "foursquare", :section => "sights", :venuePhotos => 1)
		get_info(response)
	end

	def find_venue(id)
		response = setup.venue(id, :v => 20140806)
	end

	def venue_tips(id)
		response = setup.venue_tips(id, :v => 20140806)
	end

	def get_info(api_response)
		results = []
		api_response.groups[0].items do |item|
			item.each do |i|
				location_info = geo_format
				icon_size = "32"
				image_size = "original"
				location_info[:properties][:city] = i.venue.location.city
				location_info[:properties][:venue_id] = i.venue.id
				location_info[:properties][:title] = i.venue.name
				location_info[:properties][:category] = i.venue.categories[0].name
				location_info[:geometry][:coordinates] << i.venue.location.lng
				location_info[:geometry][:coordinates] << i.venue.location.lat
				location_info[:properties][:rating] = i.venue.rating
				location_info[:properties][:icon][:iconUrl] = i.venue.categories[0].icon.prefix + "bg_" + icon_size + i.venue.categories[0].icon.suffix
				location_info[:properties][:image_url] = i.venue.photos.groups[0].items[0].prefix + image_size + i.venue.photos.groups[0].items[0].suffix
				location_info[:properties][:address] = i.venue.location.formattedAddress
				location_info[:properties][:description] = i.tips[0].text
				results << location_info
			end
		end
		results
	end

	def geo_format
	location_info = {
		:type => "Feature", 
		:geometry => {
			:type => "Point",
			:coordinates => []
		},
		:properties => {
			"marker-color": "#63b6e5",
			"marker-size": "large",
    		"marker-symbol": "rocket",
			:icon => {}	
		}
	}
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :queries

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         :authentication_keys => [:login]

attr_accessor :login

validates :username, :presence => true, :uniqueness => {:case_sensitive => false} 
validate :validate_username

def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions.to_hash).first
      end
end

def validate_username
  if User.where(email: username).exists?
    errors.add(:username, :invalid)
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
	 before_action :authenticate_user!, only: [:saved, :saved_places]
	 skip_before_action :verify_authenticity_token, only: [:near_me, :saved]

	def index
		query = Query.new
		gon.current_user = current_user
		gon.geoformat = query.geo_format
		if params[:search]
			gon.current_user = current_user
			gon.geoJSON_bylocation = query.explore_by_location(params[:search])
			@location_info = gon.geoJSON_bylocation
			render json: @location_info
		end
	end

	def saved
		query = Query.new
		response = query.find_venue(params[:venue_id])
		check_database = Query.where(user_id: current_user.id)
		user_saved = false
		
		check_database.each do |venue| 
			if venue.venue_id == params[:venue_id]
				user_saved = true
				break
			end
		end

		if user_saved == false 
			Query.create(
				city: response.location.city,
				venue_id: params[:venue_id],
				title: response.name,
				rating: response.rating,
				address: response.location.formattedAddress,
				description: "#{response.location.state}, #{response.location.country}",
				longitude: response.location.lng,
				latitude: response.location.lat,
				category: response.categories[0].name,
				user_id: current_user.id,
				icon_url: response.categories[0].icon.prefix + "bg_" + "32" + response.categories[0].icon.suffix,
				image_url: response.photos.groups[0].items[0].prefix + "original" + response.photos.groups[0].items[0].suffix
			)
		end
		render json: {saved: user_saved}
	end

	def show
		query = Query.new
		response = query.find_venue(params[:venue_id])
		tips = []
		images = []
		timings = []

		response.tips.groups[0].items.each do |item|
			if item['text'] != nil
				tips << item['text']
			end
		end

		response.photos.groups[0].items.each do |item|
			if item['prefix'] != nil
				images << item['prefix'] + "original" + item['suffix']
			end
		end
		if response['popular'] != nil
			timings << response['popular']['timeframes']
		end
		render json: {tips: tips, images: images, timings: timings}
	end

	def near_me
		if params[:coords]
		coords = params[:coords].split(",")
		lat = coords[0].to_f
		lng = coords[1].to_f
		query = Query.new
		gon.geoJSON_bycoords = query.explore_by_coords("#{lat}, #{lng}")
		@location_info = gon.geoJSON_bycoords
		render json: @location_info
		end
	end

	def saved_places
		query = Query.new
		user = User.find_by(id: current_user.id)
		places = user.queries
		geo_array = []
		places.each do |place|
			geo = query.geo_format
			geo[:geometry][:coordinates] << place.longitude
			geo[:geometry][:coordinates] << place.latitude
			geo[:properties][:city] = place.city
			geo[:properties][:title] = place.title
			geo[:properties][:rating] = place.rating
			geo[:properties][:category] = place.category
			geo[:properties][:description] = place.description
			geo_array << geo
		end
		render json: geo_array
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/layouts/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">My Title</h4>
      </div>
      <div class="modal-body">
        <div class="images">
          <ul class="modal-images">
          </ul>
        </div>
        <div class="opening-times">
          <h4></h4>
          <div class="table-responsive">
          <table class="table table-hover time-table">
          </table>
          </div>
        </div>
        <div class="tips-header"><h4></h4></div>
        <div class="tips">
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#" >LazyNomad</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     
      <%= form_tag(queries_path, :method => "get", class: "navbar-form searchForm navbar-left main-search", id: "search-form") do %>
        <%= text_field_tag "search", nil, class: "input-field", placeholder: "Where do you want to go?", type: "search" %>
         <%= button_to("Search!", queries_path, :method => "get", class: "btn btn-primary") %>
      <% end %>

      <%= form_tag("/near_me", :method => "get", class: "navbar-form navbar-left", id: "retrieveLocation") do %>
        <%= hidden_field_tag(:push_location) %>
        <%= submit_tag("Search Near Me!", class: "btn btn-primary near-me") %>
      <% end %>
    
      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to("Hello #{current_user.username}!", "#") %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to("Edit Profile", edit_user_registration_path) %></li>
            <li><a href="/saved_places" class="saved-places">My Saved Places</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to("Log out", destroy_user_session_path, method: :delete) %></li>
          </ul>
        </li>
      </ul> 
      <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to("Sign Up", new_user_registration_path) %></li>
        <li><%= link_to("Log in", new_user_session_path) %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to("Edit Profile", edit_user_registration_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to("Log out", destroy_user_session_path, method: :delete) %></li>
          </ul>
        </li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LazyNomad</title>
  <%= Gon::Base.render_data({}) %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<script src='https://api.mapbox.com/mapbox.js/v2.2.3/mapbox.js'></script>
<link href='https://api.mapbox.com/mapbox.js/v2.2.3/mapbox.css' rel='stylesheet'/>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<body>

<script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/leaflet.markercluster.js'></script>
<link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.css' rel='stylesheet' />
<link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.Default.css' rel='stylesheet' />

<%= yield %>

</body>
</html>

app/views/queries/home.html.erb
<div id="polina">
  <h1>Lazy Nomad</h1>
  <h4>Your Personal Concierge</h4>

  <%= button_to("Enter", queries_path, :method => "get", class: "enter") %>
  
</div>

  <div class="img-1"></div>
  <div class="img-2"></div>
  <div class="img-3"></div>

<script>
</script>

<style>

 


  }
</style>

app/views/queries/index.html.erb
<%= render partial: "layouts/navbar" %>
<%= render partial: "layouts/modal" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 sidebar hidden">
        <div class="row">
              <% if @location_info %>
                <% @location_info.each do |location| %>
                <div class="thumbnail venue">
                  <img class="venue-image" src= <%= location[:properties][:image_url] %> />
                  <div class="caption">
                    <form action="/saved" class="venue-form">
                    <a class="pointer"><h3 data-lng=<%= location[:geometry][:coordinates][0] %> data-lat= <%= location[:geometry][:coordinates][1] %> > <%= location[:properties][:title] %></h3></a>
                    <p><%= location[:properties][:description] %></p>
                    <p class="features"> Rating: <%= location[:properties][:rating] %> </p>
                    <p class="features"> Category: <%= location[:properties][:category] %> </p>
                    <p class="buttons"> 
                      <button class='btn btn-primary save-button' type='submit'>Save</button>
                      <button class="btn btn-default more-info" data-toggle="modal" data-target="#myModal" type='submit'>More Info</button>
                    </p>
                    <p class='venue-id' hidden><%= location[:properties][:venue_id] %></p>
                    </form>
                  </div>
                </div>
                <% end %>
            <% end %>
        </div>
    </div>
    <div class="col-md-12 main">
      <div id='map'></div>
    </div>

  </div>
</div>